### ISSUE TITLE
Audio not working on new docker installation of fruitnanny

### ISSUE THREAD

**Issue by James-h143** [ivadim/fruitnanny#33]
I have found i am getting the exact same error detailed here:
https://github.com/ivadim/fruitnanny/issues/28

This is on a new docker installation of fruitnanny for a new monitor i'm building, previously i followed the non docker installation instructions and this exact same microphone worked fine (although had some interferance).

**Comment by alogoc** [comment]
If you haven't found a solution already you can give a try to gsaudio. Pulseaudio never worked for my setup either.
I am starting gsaudio with the following arguments and it works fine with fruitnnany 

`gst-launch-1.0 -v alsasrc device=hw:1 ! queue ! audioconvert ! audioresample ! queue ! opusenc !  queue ! rtpopuspay ! queue max-size-bytes=0 max-size-buffers=0 !  queue ! udpsink host=127.0.0.1 port=5002`

**Comment by TheMage79** [comment]
Hi all,
I have the same issue, with the same error messages for pulseaudio.

Did someone come up with a solution for this yet?
@alogoc I checked the /opt/fruitnanny/bin/audio.sh 
and cannot see a difference in the arguments you provided.
Can you please elaborate what you mean with using gsaudio instead of pulseaudio?

I would be so happy if I could run the webinterface with audio and video support!
Best
Tobias

**Comment by NinjaGeoff** [comment]
> If you haven't found a solution already you can give a try to gsaudio. Pulseaudio never worked for my setup either.
> I am starting gsaudio with the following arguments and it works fine with fruitnnany
> 
> `gst-launch-1.0 -v alsasrc device=hw:1 ! queue ! audioconvert ! audioresample ! queue ! opusenc ! queue ! rtpopuspay ! queue max-size-bytes=0 max-size-buffers=0 ! queue ! udpsink host=127.0.0.1 port=5002`

Thank you for this! For whatever reason I couldn't get that to run when putting it in audio.sh, but editing the docker-compose.yml and putting that in as a command did the trick.

My setup:
Raspberry Pi Zero W
Official RPi Camera V2.1
Old AF logitech desk mic.
Raspbian Lite installed with the official Raspberry Pi Imager and fully updated as of 1/9/2021

**Comment by TheMage79** [comment]
Dear ghebert,
thank you for your answer.
I ended up with a similar approach which allowed me to get audio in the browser interface.
I put a similar pipline into a chronjob that starts at reboot. This worked for me.
My setup is a:
Raspberry Pi 4b 4GB
OV5647 Camera Sensor 
iGOKU USB microfone
Raspberry Pi full installation with updates from 01/03/2021.

So in principal it works also this way, but I still have a problem with IOS.
In safari or chrome browser I can hear the audio, but it sounds somehow scrambled. I will try different opusenc settings to solve the problem. Will post an update here.

Best
Tobias

**Comment by nine86** [comment]
Name                          Command                 State      Ports
----------------------------------------------------------------------------------
fruitnanny_fruitnanny_1        /usr/bin/entry.sh node ser ...   Up                
fruitnanny_gstreamer-audio_1   /usr/bin/entry.sh /audio_e ...   Restarting        
fruitnanny_gstreamer-video_1   /usr/bin/entry.sh gst-laun ...   Up                
fruitnanny_janus_1             /usr/bin/entry.sh /bin/sh  ...   Up                
fruitnanny_nginx_1             /docker-entrypoint.sh ngin ...   Up             


Can anyone explain why it states the audio is Restarting? I suspect it's something to do with the configuration of the mic device used? Mine is as below.

**** List of CAPTURE Hardware Devices ****
card 2: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by egoitz89** [comment]
> If you haven't found a solution already you can give a try to gsaudio. Pulseaudio never worked for my setup either.
> I am starting gsaudio with the following arguments and it works fine with fruitnnany
> 
> `gst-launch-1.0 -v alsasrc device=hw:1 ! queue ! audioconvert ! audioresample ! queue ! opusenc ! queue ! rtpopuspay ! queue max-size-bytes=0 max-size-buffers=0 ! queue ! udpsink host=127.0.0.1 port=5002`

Wow! Thanks a lot. This worked for me!  What is the best way to automatically launch this command? I've already tried putting in /opt/fruitnanny/bin/audio.sh but is not working. Should I put it in /opt/fruitnanny/docker-compose.yml? Couriusly it was commented:
```
  gstreamer-audio:
    image: ivadim/fruitnanny-gstreamer
    restart: always
    privileged: true
    network_mode: "host"
    depends_on:
      - janus
    devices:
      - "/dev/snd:/dev/snd"
#command: gst-launch-1.0 -v pulsesrc device=microphone ! audioconvert ! audioresample ! opusenc ! rtpopuspay ! queue max-size-bytes=0 max-size-buffers=0 ! udpsink host=127.0.0.1 port=5002
command: "/audio_entry.sh"
command: gst-launch-1.0 -v alsasrc device=hw:1 ! queue ! audioconvert ! audioresample ! queue ! opusenc ! queue ! rtpopuspay ! queue max-size-bytes=0 max-size-buffers=0 ! queue ! udpsink host=127.0.0.1 port=5002
```
